version: 2
jobs:
  build:
    working_directory: ~/cortinico/slidetoact
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      ANDROID_HOME: /usr/local/android-sdk-linux
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    docker:
      - image: circleci/android:api-26-alpha
      
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: if [ -a ./gradlew ]; then ./gradlew dependencies; else gradle dependencies; fi
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.bundle
        - ~/.gradle
        - /usr/local/android-sdk-linux/platforms/android-26
        - /usr/local/android-sdk-linux/build-tools/26.0.2
    
    - run:
        command: emulator -avd circleci-android22 -no-audio -no-window
        background: true
    - run: circle-android wait-for-boot
    - run: adb shell settings put global window_animation_scale 0
    - run: adb shell settings put global transition_animation_scale 0
    - run: adb shell settings put global animator_duration_scale 0
    - run: sleep 30
    - run: adb shell input keyevent 82
    - run:
        command: ./gradlew clean build lint test connectedCheck -PdisablePreDex
        no_output_timeout: 32000s
    - run: cp -r slidetoact/build/outputs $CIRCLE_ARTIFACTS
    - run: cp -r example/build/outputs $CIRCLE_ARTIFACTS
    - run: cp -r example/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results